### ISSUE TITLE
URL is not restricted

### ISSUE THREAD

**Issue by teodor-pripoae** [dyatlov/proclink-api#1]
Hi,

I think URLs should be restricted to public internet URLs. Currently `http://localhost` works, returning oembed for the server itself. File URLs are safe, through. If you are running this on an amazon instance accessing local port webserver gets an attacker access to amazon instance metadata. Also it can access any unprotected servers running on localhost or inside private network.

Pocket was hacked in a [similar way](https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/).

I'm not sure if the issue is here or in [go-url2oembed](https://github.com/dyatlov/go-url2oembed).

**Comment by dyatlov** [comment]
Hi, thank you for feedback Teodor.
Yeah, I've read about Pocket and few days ago I tested localhost myself too :) In my case it's safe because Go' http client can read from only http/https protocols and my server respond on them with default website, so no way to hack it or return any useful info from there.

But I agree that it needs to have an option to restrict access to local urls.
I'll add an option to url2oembed library to restrict it.

**Comment by teodor-pripoae** [comment]
Somebody can also enter an url with dns pointing to localhost, something like `127.0.0.1.xip.io`.  For amazon I think it is `169.254.169.254`, `169.254.169.254.xip.io`.

I'm not sure how the filtering should be done in an efficient way. Maybe allow the user to setup ignored subnet masks ? For example, if I have private network on `10.0.99.0/24`, I don't want this server to access any of the ips on this subnet. I may be running an unprotected elasticsearch HTTP API, or some other unprotected HTTP endpoint restricted to private network only.

**Comment by dyatlov** [comment]
@teodor-pripoae Look at this commit:

https://github.com/dyatlov/go-url2oembed/commit/11b15e4d9905c907fba74893280bd24dc606fc22

It's now possible to black/white list IP addresses. So now it's just a matter of adding a config to the server.

**Comment by teodor-pripoae** [comment]
I was thinking more of a netmask range. If I have a long list of internal ips or if I'm running under kubernetes, which allocates a `/16` for containers it will be a nightmare to blacklist everything, in terms of performance and configuration.

I was thinking something like:

``` go
parser.BlacklistIps = []string{
  "192.168.0.0/16",
  "10.99.0.0/16",
  "172.0.0.0/8",
}
```

If you think this solution is ok, I think I can come up with a PR next week.

**Comment by dyatlov** [comment]
@teodor-pripoae Just made it as you want: https://github.com/dyatlov/go-url2oembed/commit/78043cb7bc1936c166420fcf4e19c4037df0a282

It accepts IPNet slice as it's built-in go structure for ip ranges. I didn't include function to convert strings to IPNet because I think it shouldnt be inside the lib but I added such function in example (https://github.com/dyatlov/go-url2oembed/blob/master/examples/simple.go) and to server config (https://github.com/dyatlov/proclink-api/commit/9ddda50467aa8db62991a0a227306d05b6e92a28)

**Comment by teodor-pripoae** [comment]
Cool, thank you very much !

**Comment by dyatlov** [comment]
Yeah, to disable access to private network from now you can run the server using this command:

`./server -blacklist_ranges "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"`

I'm closing the issue now
